const Store = {
  state() {
    return {
      statistics: {
        url: 'assets/response-statistics.json',
        data: {
          ID: 4,
          SESSION_ID: 5,
        },
      },
      query: '',
      activeTradeOffer: {},
      tags: [
        {
          name: 'Пальто',
          href: '/palto/',
        },
        {
          name: 'Женщинам',
          href: '/zhenshcinam/',
        },
        {
          name: 'Зима',
          href: '/zima/',
        },
      ],
      propList: [
        { type: 'color', code: 'tyu9', name: 'Цвет' },
        { type: 'list', code: 'jkf87', name: 'Размер' },
        { type: 'list', code: 'n6', name: 'Качество' },
        { type: 'color', code: 'ght34', name: 'Другой цвет' },
        { type: 'list', code: 'b', name: 'Материал' },
      ],
      category: 'Женщинам/Одежда',
      brand: 'Lanvin',
      video:
        '<div>Video</div><div data-thumb="/upload/play.png" ><iframe width="100%" height="360" src="https://www.youtube.com/embed/_h7-0gCc_Hw" frameborder="0" allowfullscreen ></div>',
      rating: 2,
      labels: [
        {
          color: '#ca3538',
          value: '35%',
        },
        {
          color: '#528b16',
          value: 'Рекомендуем',
        },
        {
          color: '#f09e00',
          value: 'Хит',
        },
        {
          color: '#8e42b1',
          value: 'Акция',
        },
        {
          color: '#8e42b1',
          value: 'Новинка',
        },
      ],
      description: [
        {
          open: true,
          title: 'Описание',
          body: 'Элегантное, слегка укороченное однобортное пальто из <a href="">верблюжьей шерсти</a> натурального цвета. Натуральные экологичные материалы, классическая модель, идеально сочетающаяся со строгим офисным стилем и деловым casual.',
        },
        {
          open: true,
          title: 'Состав',
          body: 'Элегантное, слегка укороченное однобортное пальто из верблюжьей шерсти натурального цвета. Натуральные экологичные материалы, классическая модель, идеально сочетающаяся со строгим офисным стилем и деловым casual.',
        },
        {
          open: false,
          title: 'Доставка и возврат',
          body: 'Элегантное, слегка укороченное однобортное пальто из верблюжьей шерсти натурального цвета. Натуральные экологичные материалы, классическая модель, идеально сочетающаяся со строгим офисным стилем и деловым casual.',
        },
        {
          open: false,
          title: 'Собственные свойства',
          body: 'Элегантное, слегка укороченное однобортное пальто из верблюжьей шерсти натурального цвета. Натуральные экологичные материалы, классическая модель, идеально сочетающаяся со строгим офисным стилем и деловым casual.',
        },
      ],
      tradeOffers: [
        {
          id: 'tp1',
          price: '3 800 руб.',
          'discount-diff': '400 руб.',
          'discount-percent': '10%',
          'old-price': '4 200 руб.',
          photo: [
            '/upload/catalog.detail/1.jpg',
            '/upload/catalog.detail/2.jpg',
            '/upload/catalog.detail/3.jpg',
          ],
          'big-photo': [
            'http://assembly.2px.ru/upload/iblock/f80/f804a7769247187e7683df949a212037.jpg',
            'http://assembly.2px.ru/upload/iblock/f80/f804a7769247187e7683df949a212037.jpg',
            'http://assembly.2px.ru/upload/iblock/f80/f804a7769247187e7683df949a212037.jpg',
          ],
          num: '10',
          props: [
            { name: 'Артикул', value: 'AD006EWLXF01' },
            {
              name: 'Штрихкод',
              value: 'Текст в <a href="http://ya.ru">свойстве</a> ТП 2',
            },
          ],
          available: 'Y',
          subscribe: 'Y',
          dimensions: [
            { width: 555, height: 740 },
            { width: 555, height: 740 },
          ],
          'color-tyu9': '/upload/colors/1.jpg',
          'list-jkf87': '45',
          'list-n6': 'свежий',
          cur: 'RUB',
          'color-ght34': '/upload/colors/2.jpg',
          'list-b': 'лен',
          title: 'Верблюжье пальто лен свежий 45',
        },
        {
          id: 'tp2',
          price: '3 800 руб.',
          'discount-diff': '400 руб.',
          'discount-percent': '10%',
          'old-price': '4 200 руб.',
          photo: [
            '/upload/catalog.detail/4.jpg',
            '/upload/catalog.detail/5.jpg',
            '/upload/catalog.detail/6.jpg',
          ],
          'big-photo': [
            '/upload/catalog.detail/4.jpg',
            '/upload/catalog.detail/5.jpg',
            '/upload/catalog.detail/6.jpg',
          ],
          props: [
            { name: 'Артикул', value: 'AD006EWLXF01' },
            {
              name: 'Штрихкод',
              value: 'Текст в <a href="http://ya.ru">свойстве</a> ТП 2',
            },
          ],
          num: '2',
          available: 'Y',
          dimensions:
            "[{ 'width': 570, 'height': 570 }, { 'width': 570, 'height': 855 }]",
          'color-tyu9': '/upload/colors/3.jpg',
          'list-jkf87': '46',
          'list-n6': 'мягкий',
          cur: 'RUB',
          'color-ght34': '/upload/colors/4.jpg',
          'list-b': 'хлопок',
          title: 'Верблюжье пальто лен свежий 46',
        },
        {
          id: 'tp3',
          price: '3 800 руб.',
          'discount-diff': '400 руб.',
          'discount-percent': '10%',
          'old-price': '4 200 руб.',
          photo: [
            '/upload/catalog.detail/7.jpg',
            '/upload/catalog.detail/8.jpg',
            '/upload/catalog.detail/9.jpg',
          ],
          'big-photo': [
            '/upload/catalog.detail/7.jpg',
            '/upload/catalog.detail/8.jpg',
            '/upload/catalog.detail/9.jpg',
          ],
          props: [
            { name: 'Артикул', value: 'AD006EWLXF01' },
            { name: 'Штрихкод', value: '89919381203' },
          ],
          num: '3',
          available: 'Y',
          dimensions: [
            { width: 570, height: 570 },
            { width: 570, height: 855 },
          ],
          'color-tyu9': '/upload/colors/5.jpg',
          'list-jkf87': '47',
          'list-n6': 'теплый',
          cur: 'RUB',
          'color-ght34': '/upload/colors/6.jpg',
          'list-b': 'шелк',
          title: 'Верблюжье пальто лен свежий 47',
        },
        {
          id: 'tp4',
          price: '3 800 руб.',
          'discount-diff': '400 руб.',
          'discount-percent': '10%',
          'old-price': '4 200 руб.',
          photo: [
            '/upload/catalog.detail/10.jpg',
            '/upload/catalog.detail/11.jpg',
            '/upload/catalog.detail/12.jpg',
          ],
          'big-photo': [
            '/upload/catalog.detail/10.jpg',
            '/upload/catalog.detail/11.jpg',
            '/upload/catalog.detail/12.jpg',
          ],
          props: [
            { name: 'Артикул', value: 'AD006EWLXF01' },
            { name: 'Штрихкод', value: '89919381203' },
          ],
          num: '4',
          available: 'Y',
          dimensions: [
            { width: 570, height: 570 },
            { width: 570, height: 855 },
          ],
          'color-tyu9': '/upload/colors/7.jpg',
          'list-jkf87': '45',
          'list-n6': 'свежий',
          cur: 'RUB',
          'color-ght34': '/upload/colors/2.jpg',
          'list-b': 'лен',
          title: 'Верблюжье пальто лен свежий 45 2',
        },
        {
          id: 'tp5',
          price: '3 800 руб.',
          'discount-diff': '400 руб.',
          'discount-percent': '10%',
          'old-price': '4 200 руб.',
          photo: [
            '/upload/catalog.detail/13.jpg',
            '/upload/catalog.detail/14.jpg',
            '/upload/catalog.detail/15.jpg',
          ],
          'big-photo': [
            '/upload/catalog.detail/13.jpg',
            '/upload/catalog.detail/14.jpg',
            '/upload/catalog.detail/15.jpg',
          ],
          props: [
            { name: 'Артикул', value: 'AD006EWLXF01' },
            { name: 'Штрихкод', value: '89919381203' },
          ],
          num: '5',
          available: 'Y',
          dimensions: [
            { width: 570, height: 570 },
            { width: 570, height: 855 },
          ],
          'color-tyu9': '/upload/colors/9.jpg',
          'list-jkf87': '49',
          'list-n6': 'мягкий',
          cur: 'RUB',
          'color-ght34': '/upload/colors/10.jpg',
          'list-b': 'кожа',
          title: 'Верблюжье пальто лен свежий 49',
        },
        {
          id: 'tp6',
          price: '3 800 руб.',
          'discount-diff': '400 руб.',
          'discount-percent': '10%',
          'old-price': '4 200 руб.',
          props: [
            { name: 'Артикул', value: 'AD006EWLXF01' },
            { name: 'Штрихкод', value: '89919381203' },
          ],
          num: '6',
          available: 'Y',
          dimensions: [
            { width: 570, height: 570 },
            { width: 570, height: 855 },
          ],
          'color-tyu9': '/upload/colors/11.jpg',
          'list-jkf87': '50',
          'list-n6': 'теплый',
          cur: 'RUB',
          'color-ght34': '/upload/colors/1.jpg',
          'list-b': 'сатин',
          title: 'Верблюжье пальто лен свежий 50',
        },
        {
          id: 'tp7',
          price: '3 800 руб.',
          'discount-diff': '400 руб.',
          'discount-percent': '10%',
          'old-price': '4 200 руб.',
          photo: [
            '/upload/catalog.detail/19.jpg',
            '/upload/catalog.detail/20.jpg',
            '/upload/catalog.detail/21.jpg',
          ],
          'big-photo': ['/upload/catalog.detail/19.jpg'],
          props: [
            { name: 'Артикул', value: 'AD006EWLXF01' },
            { name: 'Штрихкод', value: '89919381203' },
          ],
          num: '7',
          available: 'Y',
          dimensions: [
            { width: 570, height: 570 },
            { width: 570, height: 855 },
          ],
          'color-tyu9': '/upload/colors/2.jpg',
          'list-jkf87': '45',
          'list-n6': 'свежий',
          cur: 'RUB',
          'color-ght34': '/upload/colors/3.jpg',
          'list-b': 'лен',
          title: 'Верблюжье пальто лен свежий 45 3',
        },
        {
          id: 'tp8',
          price: '3 800 руб.',
          'discount-diff': '400 руб.',
          'discount-percent': '10%',
          'old-price': '4 200 руб.',
          photo: [
            '/upload/catalog.detail/22.jpg',
            '/upload/catalog.detail/23.jpg',
            '/upload/catalog.detail/24.jpg',
          ],
          'big-photo': [
            '/upload/catalog.detail/22.jpg',
            '/upload/catalog.detail/23.jpg',
            '/upload/catalog.detail/24.jpg',
          ],
          props: [
            { name: 'Артикул', value: 'AD006EWLXF01' },
            { name: 'Штрихкод', value: '89919381203' },
          ],
          num: '8',
          subscribe: 'Y',
          dimensions: [
            { width: 570, height: 570 },
            { width: 570, height: 855 },
          ],
          'color-tyu9': '/upload/colors/4.jpg',
          'list-jkf87': '46',
          'list-n6': 'мягкий',
          cur: 'RUB',
          'color-ght34': '/upload/colors/5.jpg',
          'list-b': 'хлопок',
          title: 'Верблюжье пальто лен свежий 46',
        },
        {
          id: 'tp9',
          price: '3 800 руб.',
          'discount-diff': '400 руб.',
          'discount-percent': '10%',
          'old-price': '4 200 руб.',
          photo: [
            '/upload/catalog.detail/25.jpg',
            '/upload/catalog.detail/26.jpg',
            '/upload/catalog.detail/27.jpg',
          ],
          'big-photo': [
            '/upload/catalog.detail/25.jpg',
            '/upload/catalog.detail/26.jpg',
            '/upload/catalog.detail/27.jpg',
          ],
          props: [
            { name: 'Артикул', value: 'AD006EWLXF01' },
            { name: 'Штрихкод', value: '89919381203' },
          ],
          num: '9',
          subscribe: 'Y',
          dimensions: [
            { width: 570, height: 570 },
            { width: 570, height: 855 },
          ],
          'color-tyu9': '/upload/colors/6.jpg',
          'list-jkf87': '47',
          'list-n6': 'теплый',
          cur: 'RUB',
          'color-ght34': '/upload/colors/7.jpg',
          'list-b': 'шелк',
          title: 'Верблюжье пальто лен свежий 47',
        },
        {
          id: 'tp10',
          price: '3 800 руб.',
          'discount-diff': '400 руб.',
          'discount-percent': '10%',
          'old-price': '4 200 руб.',
          photo: [
            '/upload/catalog.detail/28.jpg',
            '/upload/catalog.detail/29.jpg',
            '/upload/catalog.detail/30.jpg',
            '/upload/catalog.detail/31.jpg',
          ],
          'big-photo': [
            '/upload/catalog.detail/28.jpg',
            '/upload/catalog.detail/29.jpg',
            '/upload/catalog.detail/30.jpg',
            '/upload/catalog.detail/31.jpg',
          ],
          props: [
            { name: 'Артикул', value: 'AD006EWLXF01' },
            { name: 'Штрихкод', value: '89919381203' },
          ],
          num: '10',
          subscribe: 'Y',
          dimensions: [
            { width: 570, height: 570 },
            { width: 570, height: 855 },
          ],
          'color-tyu9': '/upload/colors/8.jpg',
          'list-jkf87': '48',
          'list-n6': 'свежий',
          cur: 'RUB',
          'color-ght34': '/upload/colors/9.jpg',
          'list-b': 'вискоза',
          title: 'Верблюжье пальто лен свежий 48',
        },
        {
          id: 'tp11',
          price: '3 800 руб.',
          'discount-diff': '400 руб.',
          'discount-percent': '10%',
          'old-price': '4 200 руб.',
          photo: [
            '/upload/catalog.detail/32.jpg',
            '/upload/catalog.detail/33.jpg',
            '/upload/catalog.detail/34.jpg',
            '/upload/catalog.detail/35.jpg',
          ],
          'big-photo': [
            '/upload/catalog.detail/32.jpg',
            '/upload/catalog.detail/33.jpg',
            '/upload/catalog.detail/34.jpg',
            '/upload/catalog.detail/35.jpg',
          ],
          props: [
            { name: 'Артикул', value: 'AD006EWLXF01' },
            { name: 'Штрихкод', value: '89919381203' },
          ],
          num: '11',
          subscribe: 'Y',
          dimensions: [
            { width: 570, height: 570 },
            { width: 570, height: 855 },
          ],
          'color-tyu9': '/upload/colors/10.jpg',
          'list-jkf87': '49',
          'list-n6': 'мягкий',
          cur: 'RUB',
          'color-ght34': '/upload/colors/11.jpg',
          'list-b': 'кожа',
          title: 'Верблюжье пальто лен свежий 49',
        },
        {
          id: 'tp12',
          price: '3 800 руб.',
          'discount-diff': '400 руб.',
          'discount-percent': '10%',
          'old-price': '4 200 руб.',
          photo: [
            '/upload/catalog.detail/36.jpg',
            '/upload/catalog.detail/37.jpg',
            '/upload/catalog.detail/38.jpg',
            '/upload/catalog.detail/39.jpg',
          ],
          'big-photo': [
            '/upload/catalog.detail/36.jpg',
            '/upload/catalog.detail/37.jpg',
            '/upload/catalog.detail/38.jpg',
            '/upload/catalog.detail/39.jpg',
          ],
          props: [
            { name: 'Артикул', value: 'AD006EWLXF01' },
            { name: 'Штрихкод', value: '89919381203' },
          ],
          num: '12',
          subscribe: 'Y',
          dimensions: [
            { width: 570, height: 570 },
            { width: 570, height: 855 },
          ],
          'color-tyu9': '/upload/colors/1.jpg',
          'list-jkf87': '50',
          'list-n6': 'теплый',
          cur: 'RUB',
          'color-ght34': '/upload/colors/2.jpg',
          'list-b': 'сатин',
          title: 'Верблюжье пальто лен свежий 50',
        },
        {
          id: 'tp13',
          price: '3 800 руб.',
          'discount-diff': '400 руб.',
          'discount-percent': '10%',
          'old-price': '4 200 руб.',
          photo: [
            '/upload/catalog.detail/40.jpg',
            '/upload/catalog.detail/41.jpg',
            '/upload/catalog.detail/42.jpg',
            '/upload/catalog.detail/43.jpg',
          ],
          'big-photo': [
            '/upload/catalog.detail/40.jpg',
            '/upload/catalog.detail/41.jpg',
            '/upload/catalog.detail/42.jpg',
            '/upload/catalog.detail/43.jpg',
          ],
          props: [
            { name: 'Артикул', value: 'AD006EWLXF01' },
            { name: 'Штрихкод', value: '89919381203' },
          ],
          num: '13',
          dimensions: [
            { width: 570, height: 570 },
            { width: 570, height: 855 },
          ],
          'color-tyu9': '/upload/colors/3.jpg',
          'list-jkf87': '45',
          'list-n6': 'свежий',
          cur: 'RUB',
          'color-ght34': '/upload/colors/4.jpg',
          'list-b': 'лен',
          title: 'Верблюжье пальто лен свежий 45 4',
        },
        {
          id: 'tp14',
          price: '3 800 руб.',
          'discount-diff': '400 руб.',
          'discount-percent': '10%',
          'old-price': '4 200 руб.',
          photo: [
            '/upload/catalog.detail/44.jpg',
            '/upload/catalog.detail/45.jpg',
            '/upload/catalog.detail/46.jpg',
            '/upload/catalog.detail/47.jpg',
            '/upload/catalog.detail/48.jpg',
          ],
          'big-photo': [
            '/upload/catalog.detail/44.jpg',
            '/upload/catalog.detail/45.jpg',
            '/upload/catalog.detail/46.jpg',
            '/upload/catalog.detail/47.jpg',
            '/upload/catalog.detail/48.jpg',
          ],
          props: [
            { name: 'Артикул', value: 'AD006EWLXF01' },
            { name: 'Штрихкод', value: '89919381203' },
          ],
          num: '14',
          dimensions: [
            { width: 570, height: 570 },
            { width: 570, height: 855 },
          ],
          'color-tyu9': '/upload/colors/5.jpg',
          'list-jkf87': '46',
          'list-n6': 'мягкий',
          cur: 'RUB',
          'color-ght34': '/upload/colors/6.jpg',
          'list-b': 'хлопок',
          title: 'Верблюжье пальто лен свежий 46',
        },
        {
          id: 'tp15',
          price: '3 800 руб.',
          'discount-diff': '400 руб.',
          'discount-percent': '10%',
          'old-price': '4 200 руб.',
          photo: [
            '/upload/catalog.detail/49.jpg',
            '/upload/catalog.detail/50.jpg',
            '/upload/catalog.detail/51.jpg',
            '/upload/catalog.detail/52.jpg',
          ],
          'big-photo': [
            '/upload/catalog.detail/49.jpg',
            '/upload/catalog.detail/50.jpg',
            '/upload/catalog.detail/51.jpg',
            '/upload/catalog.detail/52.jpg',
          ],
          props: [
            { name: 'Артикул', value: 'AD006EWLXF01' },
            { name: 'Штрихкод', value: '89919381203' },
          ],
          num: '15',
          dimensions: [
            { width: 570, height: 570 },
            { width: 570, height: 855 },
          ],
          'color-tyu9': '/upload/colors/7.jpg',
          'list-jkf87': '47',
          'list-n6': 'теплый',
          cur: 'RUB',
          'color-ght34': '/upload/colors/8.jpg',
          'list-b': 'шелк',
          title: 'Верблюжье пальто лен свежий 45',
        },
        {
          id: 'tp16',
          price: '3 800 руб.',
          'discount-diff': '400 руб.',
          'discount-percent': '10%',
          'old-price': '4 200 руб.',
          photo: [
            '/upload/catalog.detail/53.jpg',
            '/upload/catalog.detail/54.jpg',
            '/upload/catalog.detail/55.jpg',
            '/upload/catalog.detail/56.jpg',
          ],
          'big-photo': [
            '/upload/catalog.detail/53.jpg',
            '/upload/catalog.detail/54.jpg',
            '/upload/catalog.detail/55.jpg',
            '/upload/catalog.detail/56.jpg',
          ],
          props: [
            { name: 'Артикул', value: 'AD006EWLXF01' },
            { name: 'Штрихкод', value: '89919381203' },
          ],
          num: '16',
          dimensions: [
            { width: 570, height: 570 },
            { width: 570, height: 855 },
          ],
          'color-tyu9': '/upload/colors/9.jpg',
          'list-jkf87': '48',
          'list-n6': 'свежий',
          cur: 'RUB',
          'color-ght34': '/upload/colors/10.jpg',
          'list-b': 'вискоза',
          title: 'Верблюжье пальто лен свежий 45',
        },
        {
          id: 'tp17',
          price: '3 800 руб.',
          'discount-diff': '400 руб.',
          'discount-percent': '10%',
          'old-price': '4 200 руб.',
          photo: [
            '/upload/catalog.detail/57.jpg',
            '/upload/catalog.detail/58.jpg',
            '/upload/catalog.detail/59.jpg',
            '/upload/catalog.detail/60.jpg',
          ],
          'big-photo': [
            '/upload/catalog.detail/57.jpg',
            '/upload/catalog.detail/58.jpg',
            '/upload/catalog.detail/59.jpg',
            '/upload/catalog.detail/60.jpg',
          ],
          props: [
            { name: 'Артикул', value: 'AD006EWLXF01' },
            { name: 'Штрихкод', value: '89919381203' },
          ],
          num: '17',
          dimensions: [
            { width: 570, height: 570 },
            { width: 570, height: 855 },
          ],
          'color-tyu9': '/upload/colors/11.jpg',
          'list-jkf87': '49',
          'list-n6': 'мягкий',
          cur: 'RUB',
          'color-ght34': '/upload/colors/1.jpg',
          'list-b': 'кожа',
          title: 'Верблюжье пальто лен свежий 45',
        },
        {
          id: 'tp18',
          price: '3 800 руб.',
          'discount-diff': '400 руб.',
          'discount-percent': '10%',
          'old-price': '4 200 руб.',
          photo: [
            '/upload/catalog.detail/61.jpg',
            '/upload/catalog.detail/62.jpg',
            '/upload/catalog.detail/63.jpg',
          ],
          'big-photo': [
            '/upload/catalog.detail/61.jpg',
            '/upload/catalog.detail/62.jpg',
            '/upload/catalog.detail/63.jpg',
          ],
          props: [
            { name: 'Артикул', value: 'AD006EWLXF01' },
            { name: 'Штрихкод', value: '89919381203' },
          ],
          num: '18',
          dimensions: [
            { width: 570, height: 570 },
            { width: 570, height: 855 },
          ],
          'color-tyu9': '/upload/colors/2.jpg',
          'list-jkf87': '50',
          'list-n6': 'теплый',
          cur: 'RUB',
          'color-ght34': '/upload/colors/3.jpg',
          'list-b': 'сатин',
          title: 'Верблюжье пальто лен свежий 45',
        },
        {
          id: 'tp19',
          price: '3 800 руб.',
          'discount-diff': '400 руб.',
          'discount-percent': '10%',
          'old-price': '4 200 руб.',
          photo: [
            '/upload/catalog.detail/1.jpg',
            '/upload/catalog.detail/2.jpg',
            '/upload/catalog.detail/3.jpg',
          ],
          'big-photo': [
            '/upload/catalog.detail/1.jpg',
            '/upload/catalog.detail/2.jpg',
            '/upload/catalog.detail/3.jpg',
          ],
          props: [
            { name: 'Артикул', value: 'AD006EWLXF01' },
            { name: 'Штрихкод', value: '89919381203' },
          ],
          num: '19',
          dimensions: [
            { width: 570, height: 570 },
            { width: 570, height: 855 },
          ],
          'color-tyu9': '/upload/colors/4.jpg',
          'list-jkf87': '45',
          'list-n6': 'свежий',
          cur: 'RUB',
          'color-ght34': '/upload/colors/5.jpg',
          'list-b': 'лен',
          title: 'Верблюжье пальто лен свежий 45',
        },
        {
          id: 'tp20',
          price: '3 800 руб.',
          'discount-diff': '400 руб.',
          'discount-percent': '10%',
          'old-price': '4 200 руб.',
          photo: [
            '/upload/catalog.detail/1.jpg',
            '/upload/catalog.detail/2.jpg',
            '/upload/catalog.detail/3.jpg',
          ],
          'big-photo': [
            '/upload/catalog.detail/1.jpg',
            '/upload/catalog.detail/2.jpg',
            '/upload/catalog.detail/3.jpg',
          ],
          props: [
            { name: 'Артикул', value: 'AD006EWLXF01' },
            { name: 'Штрихкод', value: '89919381203' },
          ],
          num: '20',
          dimensions: [
            { width: 570, height: 570 },
            { width: 570, height: 855 },
          ],
          'color-tyu9': '/upload/colors/6.jpg',
          'list-jkf87': '46',
          'list-n6': 'мягкий',
          cur: 'RUB',
          'color-ght34': '/upload/colors/7.jpg',
          'list-b': 'хлопок',
          title: 'Верблюжье пальто лен свежий 45',
        },
        {
          id: 'tp21',
          price: '3 800 руб.',
          'discount-diff': '400 руб.',
          'discount-percent': '10%',
          'old-price': '4 200 руб.',
          photo: [
            '/upload/catalog.detail/1.jpg',
            '/upload/catalog.detail/2.jpg',
            '/upload/catalog.detail/3.jpg',
          ],
          'big-photo': [
            '/upload/catalog.detail/1.jpg',
            '/upload/catalog.detail/2.jpg',
            '/upload/catalog.detail/3.jpg',
          ],
          props: [
            { name: 'Артикул', value: 'AD006EWLXF01' },
            { name: 'Штрихкод', value: '89919381203' },
          ],
          num: '21',
          dimensions: [
            { width: 570, height: 570 },
            { width: 570, height: 855 },
          ],
          'color-tyu9': '/upload/colors/8.jpg',
          'list-jkf87': '47',
          'list-n6': 'теплый',
          cur: 'RUB',
          'color-ght34': '/upload/colors/9.jpg',
          'list-b': 'шелк',
          title: 'Верблюжье пальто лен свежий 45',
        },
        {
          id: 'tp22',
          price: '3 800 руб.',
          'discount-diff': '400 руб.',
          'discount-percent': '10%',
          'old-price': '4 200 руб.',
          photo: [
            '/upload/catalog.detail/1.jpg',
            '/upload/catalog.detail/2.jpg',
            '/upload/catalog.detail/3.jpg',
          ],
          'big-photo': [
            '/upload/catalog.detail/1.jpg',
            '/upload/catalog.detail/2.jpg',
            '/upload/catalog.detail/3.jpg',
          ],
          props: [
            { name: 'Артикул', value: 'AD006EWLXF01' },
            { name: 'Штрихкод', value: '89919381203' },
          ],
          num: '22',
          dimensions: [
            { width: 570, height: 570 },
            { width: 570, height: 855 },
          ],
          'color-tyu9': '/upload/colors/10.jpg',
          'list-jkf87': '48',
          'list-n6': 'свежий',
          cur: 'RUB',
          'color-ght34': '/upload/colors/11.jpg',
          'list-b': 'вискоза',
          title: 'Верблюжье пальто лен свежий 45',
        },
        {
          id: 'tp23',
          price: '3 800 руб.',
          'discount-diff': '400 руб.',
          'discount-percent': '10%',
          'old-price': '4 200 руб.',
          photo: [
            '/upload/catalog.detail/1.jpg',
            '/upload/catalog.detail/2.jpg',
            '/upload/catalog.detail/3.jpg',
          ],
          'big-photo': [
            '/upload/catalog.detail/1.jpg',
            '/upload/catalog.detail/2.jpg',
            '/upload/catalog.detail/3.jpg',
          ],
          props: [
            { name: 'Артикул', value: 'AD006EWLXF01' },
            { name: 'Штрихкод', value: '89919381203' },
          ],
          num: '23',
          dimensions: [
            { width: 570, height: 570 },
            { width: 570, height: 855 },
          ],
          'color-tyu9': '/upload/colors/1.jpg',
          'list-jkf87': '49',
          'list-n6': 'мягкий',
          cur: 'RUB',
          'color-ght34': '/upload/colors/2.jpg',
          'list-b': 'кожа',
          title: 'Верблюжье пальто лен свежий 45',
        },
        {
          id: 'tp24',
          price: '3 800 руб.',
          'discount-diff': '400 руб.',
          'discount-percent': '10%',
          'old-price': '4 200 руб.',
          photo: [
            '/upload/catalog.detail/1.jpg',
            '/upload/catalog.detail/2.jpg',
            '/upload/catalog.detail/3.jpg',
          ],
          'big-photo': [
            '/upload/catalog.detail/1.jpg',
            '/upload/catalog.detail/2.jpg',
            '/upload/catalog.detail/3.jpg',
          ],
          props: [
            { name: 'Артикул', value: 'AD006EWLXF01' },
            { name: 'Штрихкод', value: '89919381203' },
          ],
          num: '24',
          dimensions: [
            { width: 570, height: 570 },
            { width: 570, height: 855 },
          ],
          'color-tyu9': '/upload/colors/3.jpg',
          'list-jkf87': '50',
          'list-n6': 'теплый',
          cur: 'RUB',
          'color-ght34': '/upload/colors/4.jpg',
          'list-b': 'сатин',
          title: 'Верблюжье пальто лен свежий 45',
        },
        {
          id: 'tp25',
          price: '3 800 руб.',
          'discount-diff': '400 руб.',
          'discount-percent': '10%',
          'old-price': '4 200 руб.',
          photo: [
            '/upload/catalog.detail/1.jpg',
            '/upload/catalog.detail/2.jpg',
            '/upload/catalog.detail/3.jpg',
          ],
          'big-photo': [
            '/upload/catalog.detail/1.jpg',
            '/upload/catalog.detail/2.jpg',
            '/upload/catalog.detail/3.jpg',
          ],
          props: [
            { name: 'Артикул', value: 'AD006EWLXF01' },
            { name: 'Штрихкод', value: '89919381203' },
          ],
          num: '25',
          dimensions: [
            { width: 570, height: 570 },
            { width: 570, height: 855 },
          ],
          'color-tyu9': '/upload/colors/5.jpg',
          'list-jkf87': '45',
          'list-n6': 'свежий',
          cur: 'RUB',
          'color-ght34': '/upload/colors/6.jpg',
          'list-b': 'лен',
          title: 'Верблюжье пальто лен свежий 45',
        },
        {
          id: 'tp26',
          price: '3 800 руб.',
          'discount-diff': '400 руб.',
          'discount-percent': '10%',
          'old-price': '4 200 руб.',
          photo: [
            '/upload/catalog.detail/1.jpg',
            '/upload/catalog.detail/2.jpg',
            '/upload/catalog.detail/3.jpg',
          ],
          'big-photo': [
            '/upload/catalog.detail/1.jpg',
            '/upload/catalog.detail/2.jpg',
            '/upload/catalog.detail/3.jpg',
          ],
          props: [
            { name: 'Артикул', value: 'AD006EWLXF01' },
            { name: 'Штрихкод', value: '89919381203' },
          ],
          num: '26',
          dimensions: [
            { width: 570, height: 570 },
            { width: 570, height: 855 },
          ],
          'color-tyu9': '/upload/colors/7.jpg',
          'list-jkf87': '46',
          'list-n6': 'мягкий',
          cur: 'RUB',
          'color-ght34': '/upload/colors/8.jpg',
          'list-b': 'хлопок',
          title: 'Верблюжье пальто лен свежий 45',
        },
        {
          id: 'tp27',
          price: '3 800 руб.',
          'discount-diff': '400 руб.',
          'discount-percent': '10%',
          'old-price': '4 200 руб.',
          photo: [
            '/upload/catalog.detail/1.jpg',
            '/upload/catalog.detail/2.jpg',
            '/upload/catalog.detail/3.jpg',
          ],
          'big-photo': [
            '/upload/catalog.detail/1.jpg',
            '/upload/catalog.detail/2.jpg',
            '/upload/catalog.detail/3.jpg',
          ],
          props: [
            { name: 'Артикул', value: 'AD006EWLXF01' },
            { name: 'Штрихкод', value: '89919381203' },
          ],
          num: '27',
          dimensions: [
            { width: 570, height: 570 },
            { width: 570, height: 855 },
          ],
          'color-tyu9': '/upload/colors/9.jpg',
          'list-jkf87': '47',
          'list-n6': 'теплый',
          cur: 'RUB',
          'color-ght34': '/upload/colors/10.jpg',
          'list-b': 'шелк',
          title: 'Верблюжье пальто лен свежий 45',
        },
        {
          id: 'tp28',
          price: '3 800 руб.',
          'discount-diff': '400 руб.',
          'discount-percent': '10%',
          'old-price': '4 200 руб.',
          photo: [
            '/upload/catalog.detail/1.jpg',
            '/upload/catalog.detail/2.jpg',
            '/upload/catalog.detail/3.jpg',
          ],
          'big-photo': [
            '/upload/catalog.detail/1.jpg',
            '/upload/catalog.detail/2.jpg',
            '/upload/catalog.detail/3.jpg',
          ],
          props: [
            { name: 'Артикул', value: 'AD006EWLXF01' },
            { name: 'Штрихкод', value: '89919381203' },
          ],
          num: '28',
          dimensions: [
            { width: 570, height: 570 },
            { width: 570, height: 855 },
          ],
          'color-tyu9': '/upload/colors/11.jpg',
          'list-jkf87': '48',
          'list-n6': 'свежий',
          cur: 'RUB',
          'color-ght34': '/upload/colors/1.jpg',
          'list-b': 'вискоза',
          title: 'Верблюжье пальто лен свежий 45',
        },
        {
          id: 'tp29',
          price: '3 800 руб.',
          'discount-diff': '400 руб.',
          'discount-percent': '10%',
          'old-price': '4 200 руб.',
          photo: [
            '/upload/catalog.detail/1.jpg',
            '/upload/catalog.detail/2.jpg',
            '/upload/catalog.detail/3.jpg',
          ],
          'big-photo': [
            '/upload/catalog.detail/1.jpg',
            '/upload/catalog.detail/2.jpg',
            '/upload/catalog.detail/3.jpg',
          ],
          props: [
            { name: 'Артикул', value: 'AD006EWLXF01' },
            { name: 'Штрихкод', value: '89919381203' },
          ],
          num: '29',
          dimensions: [
            { width: 570, height: 570 },
            { width: 570, height: 855 },
          ],
          'color-tyu9': '/upload/colors/2.jpg',
          'list-jkf87': '49',
          'list-n6': 'мягкий',
          cur: 'RUB',
          'color-ght34': '/upload/colors/3.jpg',
          'list-b': 'кожа',
          title: 'Верблюжье пальто лен свежий 45',
        },
        {
          id: 'tp30',
          price: '3 800 руб.',
          'discount-diff': '400 руб.',
          'discount-percent': '10%',
          'old-price': '4 200 руб.',
          photo: [
            '/upload/catalog.detail/1.jpg',
            '/upload/catalog.detail/2.jpg',
            '/upload/catalog.detail/3.jpg',
          ],
          'big-photo': [
            '/upload/catalog.detail/1.jpg',
            '/upload/catalog.detail/2.jpg',
            '/upload/catalog.detail/3.jpg',
          ],
          props: [
            { name: 'Артикул', value: 'AD006EWLXF01' },
            { name: 'Штрихкод', value: '89919381203' },
          ],
          num: '30',
          dimensions: [
            { width: 570, height: 570 },
            { width: 570, height: 855 },
          ],
          'color-tyu9': '/upload/colors/4.jpg',
          'list-jkf87': '50',
          'list-n6': 'теплый',
          cur: 'RUB',
          'color-ght34': '/upload/colors/5.jpg',
          'list-b': 'сатин',
          title: 'Верблюжье пальто лен свежий 45',
        },
        {
          id: 'tp31',
          price: '3 800 руб.',
          'discount-diff': '400 руб.',
          'discount-percent': '10%',
          'old-price': '4 200 руб.',
          photo: [
            '/upload/catalog.detail/1.jpg',
            '/upload/catalog.detail/2.jpg',
            '/upload/catalog.detail/3.jpg',
          ],
          'big-photo': [
            '/upload/catalog.detail/1.jpg',
            '/upload/catalog.detail/2.jpg',
            '/upload/catalog.detail/3.jpg',
          ],
          props: [
            { name: 'Артикул', value: 'AD006EWLXF01' },
            { name: 'Штрихкод', value: '89919381203' },
          ],
          num: '31',
          dimensions: [
            { width: 570, height: 570 },
            { width: 570, height: 855 },
          ],
          'color-tyu9': '/upload/colors/6.jpg',
          'list-jkf87': '45',
          'list-n6': 'свежий',
          cur: 'RUB',
          'color-ght34': '/upload/colors/7.jpg',
          'list-b': 'лен',
          title: 'Верблюжье пальто лен свежий 45',
        },
        {
          id: 'tp32',
          price: '3 800 руб.',
          'discount-diff': '400 руб.',
          'discount-percent': '10%',
          'old-price': '4 200 руб.',
          photo: [
            '/upload/catalog.detail/1.jpg',
            '/upload/catalog.detail/2.jpg',
            '/upload/catalog.detail/3.jpg',
          ],
          'big-photo': [
            '/upload/catalog.detail/1.jpg',
            '/upload/catalog.detail/2.jpg',
            '/upload/catalog.detail/3.jpg',
          ],
          props: [
            { name: 'Артикул', value: 'AD006EWLXF01' },
            { name: 'Штрихкод', value: '89919381203' },
          ],
          num: '32',
          dimensions: [
            { width: 570, height: 570 },
            { width: 570, height: 855 },
          ],
          'color-tyu9': '/upload/colors/8.jpg',
          'list-jkf87': '46',
          'list-n6': 'мягкий',
          cur: 'RUB',
          'color-ght34': '/upload/colors/9.jpg',
          'list-b': 'хлопок',
          title: 'Верблюжье пальто лен свежий 45',
        },
        {
          id: 'tp33',
          price: '3 800 руб.',
          'discount-diff': '400 руб.',
          'discount-percent': '10%',
          'old-price': '4 200 руб.',
          photo: [
            '/upload/catalog.detail/1.jpg',
            '/upload/catalog.detail/2.jpg',
            '/upload/catalog.detail/3.jpg',
          ],
          'big-photo': [
            '/upload/catalog.detail/1.jpg',
            '/upload/catalog.detail/2.jpg',
            '/upload/catalog.detail/3.jpg',
          ],
          props: [
            { name: 'Артикул', value: 'AD006EWLXF01' },
            { name: 'Штрихкод', value: '89919381203' },
          ],
          num: '33',
          dimensions: [
            { width: 570, height: 570 },
            { width: 570, height: 855 },
          ],
          'color-tyu9': '/upload/colors/10.jpg',
          'list-jkf87': '47',
          'list-n6': 'теплый',
          cur: 'RUB',
          'color-ght34': '/upload/colors/11.jpg',
          'list-b': 'шелк',
          title: 'Верблюжье пальто лен свежий 45',
        },
        {
          id: 'tp34',
          price: '3 800 руб.',
          'discount-diff': '400 руб.',
          'discount-percent': '10%',
          'old-price': '4 200 руб.',
          photo: [
            '/upload/catalog.detail/1.jpg',
            '/upload/catalog.detail/2.jpg',
            '/upload/catalog.detail/3.jpg',
          ],
          'big-photo': [
            '/upload/catalog.detail/1.jpg',
            '/upload/catalog.detail/2.jpg',
            '/upload/catalog.detail/3.jpg',
          ],
          props: [
            { name: 'Артикул', value: 'AD006EWLXF01' },
            { name: 'Штрихкод', value: '89919381203' },
          ],
          num: '34',
          dimensions: [
            { width: 570, height: 570 },
            { width: 570, height: 855 },
          ],
          'color-tyu9': '/upload/colors/1.jpg',
          'list-jkf87': '48',
          'list-n6': 'свежий',
          cur: 'RUB',
          'color-ght34': '/upload/colors/2.jpg',
          'list-b': 'вискоза',
          title: 'Верблюжье пальто лен свежий 45',
        },
        {
          id: 'tp35',
          price: '3 800 руб.',
          'discount-diff': '400 руб.',
          'discount-percent': '10%',
          'old-price': '4 200 руб.',
          photo: [
            '/upload/catalog.detail/1.jpg',
            '/upload/catalog.detail/2.jpg',
            '/upload/catalog.detail/3.jpg',
          ],
          'big-photo': [
            '/upload/catalog.detail/1.jpg',
            '/upload/catalog.detail/2.jpg',
            '/upload/catalog.detail/3.jpg',
          ],
          props: [
            { name: 'Артикул', value: 'AD006EWLXF01' },
            { name: 'Штрихкод', value: '89919381203' },
          ],
          num: '35',
          dimensions: [
            { width: 570, height: 570 },
            { width: 570, height: 855 },
          ],
          'color-tyu9': '/upload/colors/3.jpg',
          'list-jkf87': '49',
          'list-n6': 'мягкий',
          cur: 'RUB',
          'color-ght34': '/upload/colors/4.jpg',
          'list-b': 'кожа',
          title: 'Верблюжье пальто лен свежий 45',
        },
        {
          id: 'tp36',
          price: '3 800 руб.',
          'discount-diff': '400 руб.',
          'discount-percent': '10%',
          'old-price': '4 200 руб.',
          photo: [
            '/upload/catalog.detail/1.jpg',
            '/upload/catalog.detail/2.jpg',
            '/upload/catalog.detail/3.jpg',
          ],
          'big-photo': [
            '/upload/catalog.detail/1.jpg',
            '/upload/catalog.detail/2.jpg',
            '/upload/catalog.detail/3.jpg',
          ],
          props: [
            { name: 'Артикул', value: 'AD006EWLXF01' },
            { name: 'Штрихкод', value: '89919381203' },
          ],
          num: '36',
          dimensions: [
            { width: 570, height: 570 },
            { width: 570, height: 855 },
          ],
          'color-tyu9': '/upload/colors/5.jpg',
          'list-jkf87': '50',
          'list-n6': 'теплый',
          cur: 'RUB',
          'color-ght34': '/upload/colors/6.jpg',
          'list-b': 'сатин',
          title: 'Верблюжье пальто лен свежий 45',
        },
        {
          id: 'tp37',
          price: '3 800 руб.',
          'discount-diff': '400 руб.',
          'discount-percent': '10%',
          'old-price': '4 200 руб.',
          photo: [
            '/upload/catalog.detail/1.jpg',
            '/upload/catalog.detail/2.jpg',
            '/upload/catalog.detail/3.jpg',
          ],
          'big-photo': [
            '/upload/catalog.detail/1.jpg',
            '/upload/catalog.detail/2.jpg',
            '/upload/catalog.detail/3.jpg',
          ],
          props: [
            { name: 'Артикул', value: 'AD006EWLXF01' },
            { name: 'Штрихкод', value: '89919381203' },
          ],
          num: '37',
          dimensions: [
            { width: 570, height: 570 },
            { width: 570, height: 855 },
          ],
          'color-tyu9': '/upload/colors/7.jpg',
          'list-jkf87': '45',
          'list-n6': 'свежий',
          cur: 'RUB',
          'color-ght34': '/upload/colors/8.jpg',
          'list-b': 'лен',
          title: 'Верблюжье пальто лен свежий 45',
        },
        {
          id: 'tp38',
          price: '3 800 руб.',
          'discount-diff': '400 руб.',
          'discount-percent': '10%',
          'old-price': '4 200 руб.',
          photo: [
            '/upload/catalog.detail/1.jpg',
            '/upload/catalog.detail/2.jpg',
            '/upload/catalog.detail/3.jpg',
          ],
          'big-photo': [
            '/upload/catalog.detail/1.jpg',
            '/upload/catalog.detail/2.jpg',
            '/upload/catalog.detail/3.jpg',
          ],
          props: [
            { name: 'Артикул', value: 'AD006EWLXF01' },
            { name: 'Штрихкод', value: '89919381203' },
          ],
          num: '38',
          dimensions: [
            { width: 570, height: 570 },
            { width: 570, height: 855 },
          ],
          'color-tyu9': '/upload/colors/9.jpg',
          'list-jkf87': '46',
          'list-n6': 'мягкий',
          cur: 'RUB',
          'color-ght34': '/upload/colors/10.jpg',
          'list-b': 'хлопок',
          title: 'Верблюжье пальто лен свежий 45',
        },
        {
          id: 'tp39',
          price: '3 800 руб.',
          'discount-diff': '400 руб.',
          'discount-percent': '10%',
          'old-price': '4 200 руб.',
          photo: [
            '/upload/catalog.detail/1.jpg',
            '/upload/catalog.detail/2.jpg',
            '/upload/catalog.detail/3.jpg',
          ],
          'big-photo': [
            '/upload/catalog.detail/1.jpg',
            '/upload/catalog.detail/2.jpg',
            '/upload/catalog.detail/3.jpg',
          ],
          props: [
            { name: 'Артикул', value: 'AD006EWLXF01' },
            { name: 'Штрихкод', value: '89919381203' },
          ],
          num: '39',
          dimensions: [
            { width: 570, height: 570 },
            { width: 570, height: 855 },
          ],
          'color-tyu9': '/upload/colors/11.jpg',
          'list-jkf87': '47',
          'list-n6': 'теплый',
          cur: 'RUB',
          'color-ght34': '/upload/colors/1.jpg',
          'list-b': 'шелк',
          title: 'Верблюжье пальто лен свежий 45',
        },
        {
          id: 'tp40',
          price: '3 800 руб.',
          'discount-diff': '400 руб.',
          'discount-percent': '10%',
          'old-price': '4 200 руб.',
          photo: [
            '/upload/catalog.detail/1.jpg',
            '/upload/catalog.detail/2.jpg',
            '/upload/catalog.detail/3.jpg',
          ],
          'big-photo': [
            '/upload/catalog.detail/1.jpg',
            '/upload/catalog.detail/2.jpg',
            '/upload/catalog.detail/3.jpg',
          ],
          props: [
            { name: 'Артикул', value: 'AD006EWLXF01' },
            { name: 'Штрихкод', value: '89919381203' },
          ],
          num: '40',
          dimensions: [
            { width: 570, height: 570 },
            { width: 570, height: 855 },
          ],
          'color-tyu9': '/upload/colors/2.jpg',
          'list-jkf87': '48',
          'list-n6': 'свежий',
          cur: 'RUB',
          'color-ght34': '/upload/colors/3.jpg',
          'list-b': 'вискоза',
          title: 'Верблюжье пальто лен свежий 45',
        },
        {
          id: 'tp41',
          price: '3 800 руб.',
          'discount-diff': '400 руб.',
          'discount-percent': '10%',
          'old-price': '4 200 руб.',
          photo: [
            '/upload/catalog.detail/1.jpg',
            '/upload/catalog.detail/2.jpg',
            '/upload/catalog.detail/3.jpg',
          ],
          'big-photo': [
            '/upload/catalog.detail/1.jpg',
            '/upload/catalog.detail/2.jpg',
            '/upload/catalog.detail/3.jpg',
          ],
          props: [
            { name: 'Артикул', value: 'AD006EWLXF01' },
            { name: 'Штрихкод', value: '89919381203' },
          ],
          num: '41',
          dimensions: [
            { width: 570, height: 570 },
            { width: 570, height: 855 },
          ],
          'color-tyu9': '/upload/colors/4.jpg',
          'list-jkf87': '49',
          'list-n6': 'мягкий',
          cur: 'RUB',
          'color-ght34': '/upload/colors/5.jpg',
          'list-b': 'кожа',
          title: 'Верблюжье пальто лен свежий 45',
        },
      ],
    };
  },
  getters: {
    propsArray(state) {
      const result = [];
      state.propList.forEach((prop) => {
        const propsSet = new Set();
        state.tradeOffers.forEach((tradeOffer) => {
          propsSet.add(tradeOffer[`${prop.type}-${prop.code}`]);
        });

        result.push({ prop, propsSet });
      });
      return result;
    },
    activeTradeOfferIndex(state) {
      if (state.query) {
        return state.tradeOffers.findIndex((tradeOffer) => {
          return tradeOffer.id === state.query.product_id;
        });
      }
      return 0;
    },
    activeTradeOffer(state, getters) {
      return state.tradeOffers[getters.activeTradeOfferIndex];
    },
  },
  mutations: {
    setQuery(state, queryObject) {
      state.query = queryObject;
    },
  },
  actions: {
    sendStatistics: async ({ state, getters }) => {
      if (getters.activeTradeOffer.id === state.query.product_id) {
        return;
      }

      let formData = new FormData(),
        controller = new AbortController(),
        response,
        result;
      Object.keys(state.statistics).forEach((key) => {
        formData.set(key, state.statistics[key]);
      });
      formData.set('PRODUCT_ID', getters.activeTradeOfferIndex.id);
      setTimeout(() => {
        if (!response) {
          controller.abort();
        }
      }, 20000);
      response = await fetch(
        state.statistics.url /*, {
          method: 'POST',
          body: formData,
          signal: controller.signal,
        }*/
      );
      result = await response.json();
      if (result && typeof result === 'object') {
        if (result.errors) {
          console.log(result.errors[0].message);
        }
      }
    },
  },
};

export default Store;
